with TRIPS as(
    select
	RIDE_ID,
	RIDEABLE_TYPE,
	DATEADD(YEAR,-5,DATE(TO_TIMESTAMP (STARTED_AT))) AS TRIP_DATE,
    START_STATIO_ID  as START_STATION_ID  ,
	END_STATION_ID ,
	MEMBER_CSUAL as MEMBER_CASUAL,
    TIMESTAMPDIFF(SECOND ,DATEADD(YEAR,-5,TO_TIMESTAMP (STARTED_AT)),DATEADD(YEAR,-5,TO_TIMESTAMP (ENDED_AT))) AS TRIP_DURATION_SECONDS,    
    from {{ source('DEMO', 'BIKE') }}
    where ride_id  <>'ride_id'

)

select * from TRIPS


